vscode裡，open source的function可以右鍵：移至定義

In [ ]:
import numpy as np
np.random.random() #0到1之間隨機一個數

0.05233016849039174

In [ ]:
np.random.random(size=3) #引數名稱的呼叫
np.random.random(3) #引數值呼叫，呼叫出一個實體

array([0.51716481, 0.12397429, 0.80242127])

In [3]:
np.random.random((3,4)) #第一維3個數，第二維4個數

array([[0.50523418, 0.30597   , 0.34521134, 0.93172904],
       [0.93267172, 0.55607604, 0.02618824, 0.61433688],
       [0.76906463, 0.08915519, 0.93574642, 0.09406786]])

In [19]:
from numpy.random import normal #從numpy這個package裡的module（random）導入normal這個function
nm = normal(size=(3,4),loc=100,scale=1) #引數名稱的呼叫不用照順序
print(type(nm))
print(nm)

<class 'numpy.ndarray'>
[[101.71427594 101.70759077 100.5364456   99.25095071]
 [ 99.86594296 100.48225075  99.7309551   99.42449279]
 [100.63717194 100.127792   101.27511157 100.26305914]]


ndarray的實體，可以做陣列運算（矩陣），也可以跑統計
- 常用的實體屬性
 - ndim
 - size
 - shape
 - dtype
- 常用的實體方法
 - sum()
 - mean()

In [ ]:
print(nm.ndim) #幾維
print(nm.size) #大小（總共幾個元素）
print(nm.shape) #各維大小
print(nm.dtype) #元素的type

2
12
(3, 4)
float64


In [ ]:
nm.sum() #nm的所有數值加總

np.float64(1198.8045318960776)

In [20]:
sum0 = nm.sum(axis=0) #第一維加總
sum1 = nm.sum(axis=1) #第二維加總
print(sum0)
print(sum1)

[302.21739084 302.31763352 301.54251227 298.93850264]
[403.20926301 399.5036416  402.30313466]


In [ ]:
np.random.seed(112) #隨機種子，用這個生成的隨機亂數就會是固定的，重跑也會一樣
card = np.random.randint(1,21,size=(26,5)) #隨機生成1~20的整數（21不算）
#第一維：26個角色；第二維：每個角色5個屬性
card

array([[ 5, 12,  9,  2,  6],
       [13,  8,  9, 10, 11],
       [17,  5,  9,  7, 17],
       [20,  6,  6,  9,  4],
       [18, 11, 11,  6, 19],
       [15, 17, 11, 17, 14],
       [ 1,  9,  3, 14, 15],
       [15,  3,  2,  4,  3],
       [ 4,  1, 14,  8,  9],
       [ 3, 10, 11, 18,  8],
       [10,  7, 12, 11,  3],
       [14, 12, 18,  3, 20],
       [ 9,  8,  8, 20,  1],
       [12, 11, 14,  6, 11],
       [ 5, 12,  5, 17, 13],
       [ 3, 11, 15,  8, 13],
       [ 2,  2, 16, 20, 16],
       [10,  3,  6,  4, 10],
       [ 7, 18, 14, 18, 20],
       [ 6, 13,  6, 16, 17],
       [ 7,  1,  8, 12, 16],
       [13, 18, 17, 14,  8],
       [ 3,  8, 13, 19,  1],
       [12,  9, 10,  7,  8],
       [ 7,  8,  4, 16,  3],
       [17, 10,  4, 13, 15]], dtype=int32)

panda （https://pandas.pydata.org/docs/reference/index.html）
 - function
 - class（通常第一個字是大寫）
  - serious：一維資料（list、dictionary）
  - dataframe：二維資料表格
  - 2個serious就可以組成dataframe（有直的serious也有橫的serious）
- 常數

一個dataframe有2個Index實體：
- 欄：columns
- 列：index



In [ ]:
#建立dataframe
import pandas as pd

cardDF = pd.DataFrame(data=card, 
            columns=['綠','藍','粉','橘','紫'], 
            index=[f"角色{x}" for x in range(1,27)]) #用list的comprehension
cardDF

綠   藍   粉   橘   紫
角色1    5  12   9   2   6
角色2   13   8   9  10  11
角色3   17   5   9   7  17
角色4   20   6   6   9   4
角色5   18  11  11   6  19
角色6   15  17  11  17  14
角色7    1   9   3  14  15
角色8   15   3   2   4   3
角色9    4   1  14   8   9
角色10   3  10  11  18   8
角色11  10   7  12  11   3
角色12  14  12  18   3  20
角色13   9   8   8  20   1
角色14  12  11  14   6  11
角色15   5  12   5  17  13
角色16   3  11  15   8  13
角色17   2   2  16  20  16
角色18  10   3   6   4  10
角色19   7  18  14  18  20
角色20   6  13   6  16  17
角色21   7   1   8  12  16
角色22  13  18  17  14   8
角色23   3   8  13  19   1
角色24  12   9  10   7   8
角色25   7   8   4  16   3
角色26  17  10   4  13  15

list的綜合表達式（comprehension）

一串x從0到9的平方的list：
```
[x**2 for x in range(10)]
```

In [ ]:
[x**2 for x in range(10) if x < 4] #如果x<4，就做for in 

[0, 1, 4, 9]

In [33]:
print(type(cardDF))
print(type(cardDF.columns))
print(type(cardDF.index))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>


In [ ]:
cardDF.columns.name = "卡面屬性" #columns名稱
cardDF.index.name = "角色" #index名稱
cardDF

卡面屬性   綠   藍   粉   橘   紫
角色                      
角色1    5  12   9   2   6
角色2   13   8   9  10  11
角色3   17   5   9   7  17
角色4   20   6   6   9   4
角色5   18  11  11   6  19
角色6   15  17  11  17  14
角色7    1   9   3  14  15
角色8   15   3   2   4   3
角色9    4   1  14   8   9
角色10   3  10  11  18   8
角色11  10   7  12  11   3
角色12  14  12  18   3  20
角色13   9   8   8  20   1
角色14  12  11  14   6  11
角色15   5  12   5  17  13
角色16   3  11  15   8  13
角色17   2   2  16  20  16
角色18  10   3   6   4  10
角色19   7  18  14  18  20
角色20   6  13   6  16  17
角色21   7   1   8  12  16
角色22  13  18  17  14   8
角色23   3   8  13  19   1
角色24  12   9  10   7   8
角色25   7   8   4  16   3
角色26  17  10   4  13  15

有一個叫df的dataframe
- df[]：df的subscript（欄位名稱）
- 

In [36]:
cardDF['藍']

角色
角色1     12
角色2      8
角色3      5
角色4      6
角色5     11
角色6     17
角色7      9
角色8      3
角色9      1
角色10    10
角色11     7
角色12    12
角色13     8
角色14    11
角色15    12
角色16    11
角色17     2
角色18     3
角色19    18
角色20    13
角色21     1
角色22    18
角色23     8
角色24     9
角色25     8
角色26    10
Name: 藍, dtype: int32

In [ ]:
sum_card = cardDF['藍']+ cardDF['粉'] + cardDF['橘'] + cardDF['紫'] + cardDF['綠'] #五個欄加總
average_card = sum_card / 5 #五欄平均
#加入新欄位
cardDF['卡面總數'] = sum_card 
cardDF['平均卡面數'] = average_card
cardDF

卡面屬性   綠   藍   粉   橘   紫  卡面總數  平均卡面數
角色                                   
角色1    5  12   9   2   6    34    6.8
角色2   13   8   9  10  11    51   10.2
角色3   17   5   9   7  17    55   11.0
角色4   20   6   6   9   4    45    9.0
角色5   18  11  11   6  19    65   13.0
角色6   15  17  11  17  14    74   14.8
角色7    1   9   3  14  15    42    8.4
角色8   15   3   2   4   3    27    5.4
角色9    4   1  14   8   9    36    7.2
角色10   3  10  11  18   8    50   10.0
角色11  10   7  12  11   3    43    8.6
角色12  14  12  18   3  20    67   13.4
角色13   9   8   8  20   1    46    9.2
角色14  12  11  14   6  11    54   10.8
角色15   5  12   5  17  13    52   10.4
角色16   3  11  15   8  13    50   10.0
角色17   2   2  16  20  16    56   11.2
角色18  10   3   6   4  10    33    6.6
角色19   7  18  14  18  20    77   15.4
角色20   6  13   6  16  17    58   11.6
角色21   7   1   8  12  16    44    8.8
角色22  13  18  17  14   8    70   14.0
角色23   3   8  13  19   1    44    8.8
角色24  12   9  10   7   8    46    9.2
角色25   7   8   4  16   3    38    7.6
角色26  17  10   4  13  15    59   11.8