vscode裡，open source的function可以右鍵：移至定義

In [ ]:
import numpy as np
np.random.random() #0到1之間隨機一個數

0.05233016849039174

In [ ]:
np.random.random(size=3) #引數名稱的呼叫
np.random.random(3) #引數值呼叫，呼叫出一個實體

array([0.51716481, 0.12397429, 0.80242127])

In [3]:
np.random.random((3,4)) #第一維3個數，第二維4個數

array([[0.50523418, 0.30597   , 0.34521134, 0.93172904],
       [0.93267172, 0.55607604, 0.02618824, 0.61433688],
       [0.76906463, 0.08915519, 0.93574642, 0.09406786]])

In [19]:
from numpy.random import normal #從numpy這個package裡的module（random）導入normal這個function
nm = normal(size=(3,4),loc=100,scale=1) #引數名稱的呼叫不用照順序
print(type(nm))
print(nm)

<class 'numpy.ndarray'>
[[101.71427594 101.70759077 100.5364456   99.25095071]
 [ 99.86594296 100.48225075  99.7309551   99.42449279]
 [100.63717194 100.127792   101.27511157 100.26305914]]


ndarray的實體，可以做陣列運算（矩陣），也可以跑統計
- 常用的實體屬性
 - ndim
 - size
 - shape
 - dtype
- 常用的實體方法
 - sum()
 - mean()

In [ ]:
print(nm.ndim) #幾維
print(nm.size) #大小（總共幾個元素）
print(nm.shape) #各維大小
print(nm.dtype) #元素的type

2
12
(3, 4)
float64


In [ ]:
nm.sum() #nm的所有數值加總

np.float64(1198.8045318960776)

In [20]:
sum0 = nm.sum(axis=0) #第一維加總
sum1 = nm.sum(axis=1) #第二維加總
print(sum0)
print(sum1)

[302.21739084 302.31763352 301.54251227 298.93850264]
[403.20926301 399.5036416  402.30313466]
